let project;
let projects = [];
let viewStage;
let artifactReadOnly = false;
let integration = { providers: { openai: { configured: false }, compatible: { configured: false } }, adapters: [] };
const $ = (selector) => document.querySelector(selector);
const toast = $("#toast");
let toastTimer;

function say(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add("show"); toastTimer = setTimeout(() => toast.classList.remove("show"), 3200); }
function escapeHtml(value) { const div = document.createElement("div"); div.textContent = String(value || ""); return div.innerHTML; }
function readableSize(bytes) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.ceil(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
async function request(url, options) { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) throw new Error(body.error || "请求失败。"); return body; }
function stageStatus(index) { const stageId = project.stages[index].id; if (project.invalidatedStages?.includes(stageId)) return index === project.currentStage ? "待重新确认" : "待复核"; return index < project.currentStage ? "已确认" : index === project.currentStage ? "待确认" : "未开始"; }
function currentArtifact() { return project.artifacts?.[project.stages[viewStage].id]?.content || (viewStage === 1 ? project.brief : project.stages[viewStage].summary); }
function projectStatus(item) { return item.reviewPassed ? "已完成" : `进行至 ${String(item.currentStage).padStart(2, "0")} 阶段`; }
function projectContext() { return [project.brief, ...Object.values(project.artifacts || {}).map((artifact) => artifact?.content || ""), ...(project.uploads || []).map((file) => `${file.kind} ${file.name}`)].join("\n").toLowerCase(); }
function autoAdapterId(stageIndex = project.currentStage) { const context = projectContext(); if (stageIndex === 3) return /midjourney|\bmj\b|外部出图/.test(context) ? "midjourney-prompt" : "built-in-image-prompt"; if (stageIndex === 7 || stageIndex === 8) return /首帧|尾帧|首尾帧|已有视频|视频编辑|短片|15秒以内|15 秒以内/.test(context) ? "minimax-h3-prompt" : "seedance-25-prompt"; if (!integration.providers?.openai?.configured && integration.providers?.compatible?.configured) return "compatible-text"; return [1, 4, 6, 9].includes(stageIndex) ? "openai-terra" : "openai-luna"; }
function autoAdapterReason(stageIndex = project.currentStage) { const id = autoAdapterId(stageIndex); if (id === "midjourney-prompt") return "检测到 Midjourney / 外部出图偏好"; if (id === "built-in-image-prompt") return "资产开发默认使用内置图像路线"; if (id === "minimax-h3-prompt") return "检测到首尾帧、短片或已有视频编辑需求"; if (id === "seedance-25-prompt") return "视频阶段优先连续叙事与多参考能力"; if (id === "compatible-text") return "OpenAI 未连接，自动降级到兼容文本接口"; return id === "openai-terra" ? "当前阶段需要较强的创作与审核推理" : "当前阶段以结构化整理为主"; }
function adapterForStage(stageIndex = project.currentStage) { return integration.adapters.find((adapter) => adapter.id === autoAdapterId(stageIndex)) || null; }
function adapterReady(adapter) { return Boolean(adapter) && (adapter.provider === "prompt" || integration.providers?.[adapter.provider]?.configured); }

function renderProjects() {
  $("#projectList").innerHTML = projects.map((item) => `<button class="project-card ${item.id === project.id ? "active" : ""}" data-project-id="${item.id}"><span class="project-icon">◈</span><span><strong>${escapeHtml(item.name)}</strong><small>${projectStatus(item)}</small></span><span class="project-more">›</span></button>`).join("");
  document.querySelectorAll("[data-project-id]").forEach((button) => button.addEventListener("click", () => switchProject(button.dataset.projectId)));
}
function renderNavigation() {
  $("#stageNav").innerHTML = project.stages.map((stage, index) => { const needsRecheck = project.invalidatedStages?.includes(stage.id); const completed = index < project.currentStage && !needsRecheck; return `<button class="stage-button ${index === viewStage ? "active" : ""} ${completed ? "complete" : ""}" data-stage="${index}" ${index > project.currentStage ? "disabled" : ""}><span class="stage-index">${needsRecheck ? "↺" : completed ? "✓" : String(index).padStart(2, "0")}</span><span class="stage-label">${stage.label}</span></button>`; }).join("");
  document.querySelectorAll(".stage-button").forEach((button) => button.addEventListener("click", () => { viewStage = Number(button.dataset.stage); render(); }));
}
function renderActivity() { $("#activityList").innerHTML = project.activity.slice(0, 4).map((entry, index) => `<div class="activity"><span class="activity-mark">${index === 0 ? "✓" : "•"}</span><p>${escapeHtml(entry.message)}<br><small>${index === 0 ? "当前版本" : "项目记录"}</small></p><time>${new Date(entry.at).toLocaleString("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" })}</time></div>`).join(""); }
function renderUploads() { const uploads = project.uploads || []; $("#uploadList").innerHTML = uploads.length ? uploads.slice(0, 4).map((file) => `<li class="upload-item"><span class="upload-icon">${file.kind === "剧本" ? "文" : file.kind === "资产" ? "资" : "参"}</span><span><strong title="${escapeHtml(file.name)}">${escapeHtml(file.name)}</strong><small>${file.kind} · ${readableSize(file.size)}</small></span></li>`).join("") : `<li class="upload-empty">还没有项目文件</li>`; }
function renderIntegration() {
  const adapter = adapterForStage(); const ready = adapterReady(adapter); const button = $("#openIntegrationDialog");
  button.textContent = "模型中心"; button.classList.toggle("connected", ready);
  $("#selectedModel").textContent = adapter ? `${adapter.label}${adapter.multimodal ? " · 多模态" : " · 提示词"} · 自动：${autoAdapterReason()}` : "等待系统识别";
  const generate = $("#generateDraft"); generate.textContent = adapter?.outputMode === "prompt" ? "输出适配提示词" : "模型生成草稿"; generate.disabled = !ready || project.reviewPassed;
}
function render() {
  const stage = project.stages[viewStage]; const isCurrentStage = viewStage === project.currentStage; const canReturn = viewStage < project.currentStage; const isDone = project.reviewPassed;
  $("#projectNameTop").textContent = project.name;
  $("#stageEyebrow").textContent = `${stage.id} · ${stage.workflow.replace("_workflow.md", "").replaceAll("_", " ").toUpperCase()}`;
  $("#stageTitle").textContent = stage.label; $("#stageDescription").textContent = stage.description;
  $("#artifactTitle").textContent = stage.artifact; $("#artifactStatus").textContent = isDone ? "已完成" : stageStatus(viewStage); $("#artifactStatus").classList.toggle("complete", isDone || viewStage < project.currentStage);
  $("#artifactBody").innerHTML = `<h3>工作摘要</h3><p>${escapeHtml(currentArtifact())}</p><div class="fact-grid"><div class="fact"><small>工作流</small><strong>${stage.workflow}</strong></div><div class="fact"><small>状态</small><strong>${stageStatus(viewStage)}</strong></div><div class="fact"><small>版本</small><strong>REV-${String(project.revision).padStart(4, "0")}</strong></div></div>`;
  $("#revision").textContent = `REV-${String(project.revision).padStart(4, "0")} · ${new Date(project.updatedAt).toLocaleString("zh-CN")}`;
  $("#currentState").textContent = project.stages[project.currentStage].id;
  $("#scriptStatus").textContent = project.currentStage === 0 ? "Source Material" : project.currentStage === 1 ? "Optimized Proposal" : "Production-Locked";
  $("#nextWorkflow").textContent = isDone ? "Project Complete / Post" : project.stages[project.currentStage + 1]?.workflow || "13_review_workflow.md";
  $("#progressText").textContent = `${project.currentStage + 1} / ${project.stages.length} 阶段`; $("#progressFill").style.width = `${((project.currentStage + 1) / project.stages.length) * 100}%`;
  $("#progressHint").textContent = project.returnRoute ? `已返回 ${project.returnRoute}；后续阶段的成果已保留，需依次重新核验。` : isDone ? "审核已通过，项目已完成。" : `完成${project.stages[project.currentStage].label}后，将进入${project.stages[project.currentStage + 1]?.label || "审核通过"}。`;
  $("#checkCount").textContent = canReturn ? "可返回修改" : isCurrentStage ? "2 / 3" : "已确认";
  $("#checklist").innerHTML = ["当前工件已保存", "上一阶段事实已继承", canReturn ? "返回后可修改，并重新核验后续阶段" : isCurrentStage ? "等待用户确认" : "阶段已确认"].map((item, i) => `<li><span class="check-dot ${canReturn || !isCurrentStage || i < 2 ? "done" : ""}">${canReturn || !isCurrentStage || i < 2 ? "✓" : ""}</span><span>${item}</span></li>`).join("");
  $("#advanceStage").disabled = (!isCurrentStage && !canReturn) || (isDone && !canReturn); $("#advanceStage").innerHTML = canReturn ? "返回此步骤继续 <span>↩</span>" : isDone ? "项目已完成 <span>✓</span>" : "确认并下一步 <span>→</span>";
  renderProjects(); renderNavigation(); renderActivity(); renderUploads(); renderIntegration();
}
async function refreshProjectList() { const response = await request("/api/projects"); projects = response.projects; }
async function refreshIntegration() { integration = await request("/api/integrations/models"); }
async function switchProject(id) { try { project = await request(`/api/projects/${id}`); viewStage = project.currentStage; render(); say(`已切换到《${project.name}》`); } catch (error) { say(error.message); } }
async function confirmStage() { try { if (viewStage < project.currentStage) { const target = project.stages[viewStage]; project = await request(`/api/projects/${project.id}/actions/return`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ stageId: target.id }) }); viewStage = project.currentStage; await refreshProjectList(); render(); say(`已返回 ${target.id}；后续内容已保留，等待重新核验`); return; } project = await request(`/api/projects/${project.id}/actions/confirm`, { method: "POST" }); viewStage = project.currentStage; await refreshProjectList(); render(); say("已写入项目状态，并进入下一工序"); } catch (error) { say(error.message); } }
async function generateDraft() { const adapter = adapterForStage(); if (!adapter) return say("系统暂未识别到适用于当前步骤的模型。"); const button = $("#generateDraft"), label = button.textContent; button.disabled = true; button.textContent = adapter.outputMode === "prompt" ? "正在整理提示词…" : "模型正在生成…"; try { project = await request(`/api/projects/${project.id}/agent/draft`, { method: "POST" }); await refreshProjectList(); render(); say(adapter.outputMode === "prompt" ? "适配提示词已保存，请复制到外部模型使用" : "模型草稿已保存，请审阅后确认"); } catch (error) { say(error.message); } finally { button.textContent = label; renderIntegration(); } }

const projectDialog = $("#projectDialog"), artifactDialog = $("#artifactDialog"), uploadDialog = $("#uploadDialog"), integrationDialog = $("#integrationDialog");
function closeDialog(dialog, form) { dialog.close(); form.reset(); }
function updateUploadSelection() { const files = [...$("#uploadFiles").files]; $("#uploadSelection").textContent = files.length ? `已选择 ${files.length} 个文件：${files.map((file) => file.name).join("、")}` : "尚未选择文件"; }
function closeUploadDialog() { closeDialog(uploadDialog, $("#uploadForm")); updateUploadSelection(); }
function toBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error(`无法读取文件：${file.name}`)); reader.onload = () => resolve(String(reader.result).split(",", 2)[1]); reader.readAsDataURL(file); }); }
function openArtifactDialog(readOnly) { artifactReadOnly = readOnly; const stage = project.stages[viewStage]; $("#artifactDialogEyebrow").textContent = `${stage.id} · ${stage.label}`; $("#artifactDialogTitle").textContent = readOnly ? stage.artifact : `编辑${stage.artifact}`; $("#artifactContent").value = currentArtifact(); $("#artifactContent").readOnly = readOnly; $("#artifactDialogNote").textContent = readOnly ? "这是已保存的工件内容。点击关闭可返回工作台。" : "保存后会创建新的项目版本，并记录到项目活动中。"; $("#saveArtifact").hidden = readOnly; artifactDialog.showModal(); }
function populateAdapterChoices() { const adapters = integration.adapters.filter((adapter) => adapter.provider !== "prompt"); $("#modelAdapter").innerHTML = `<option value="">不修改 API 连接</option>${adapters.map((adapter) => `<option value="${adapter.id}">${adapter.label}${adapter.multimodal ? " · 多模态" : " · 文本"}</option>`).join("")}`; updateAdapterConfigUi(); }
function updateAdapterConfigUi() { const adapter = integration.adapters.find((item) => item.id === $("#modelAdapter").value); const isCompatible = adapter?.provider === "compatible"; const providerConfigured = adapterReady(adapter); $("#adapterDescription").textContent = adapter?.description || "只需在此处连接 API 一次；每个制作步骤会自动识别并调用合适模型。"; $("#apiKeyLabel").hidden = !adapter; $("#compatibleUrlField").hidden = !isCompatible; $("#compatibleModelField").hidden = !isCompatible; $("#openAiApiKey").required = Boolean(adapter && !providerConfigured); $("#integrationNote").textContent = !adapter ? "不需要为每个步骤设置模型。选择提供方并保存，即可统一连接。" : providerConfigured ? "该提供方已在本次服务中连接。可留空密钥复用连接，或者粘贴新密钥重新测试。" : "密钥仅存在当前本地服务内存，重启服务后会自动清除。测试连接只发送固定测试文本。"; $("#testIntegration").textContent = adapter ? "测试并保存连接 →" : "关闭模型中心"; }
function openIntegrationDialog() { $("#integrationEyebrow").textContent = "统一 API 配置"; $("#modelStageName").value = "系统会按制作步骤与项目素材自动识别并调用模型"; populateAdapterChoices(); integrationDialog.showModal(); }

$("#advanceStage").addEventListener("click", confirmStage); $("#generateDraft").addEventListener("click", generateDraft); $("#editStage").addEventListener("click", () => viewStage === project.currentStage ? openArtifactDialog(false) : say("请先点击“返回此步骤继续”，再修改历史阶段内容。")); $("#viewArtifact").addEventListener("click", () => openArtifactDialog(true));
$("#openProjectDialog").addEventListener("click", () => projectDialog.showModal()); $("#openIntegrationDialog").addEventListener("click", openIntegrationDialog); $("#modelAdapter").addEventListener("change", updateAdapterConfigUi); $("#openUploadDialog").addEventListener("click", () => uploadDialog.showModal()); $("#openUploadFromPanel").addEventListener("click", () => uploadDialog.showModal());
document.querySelectorAll("[data-close-project-dialog]").forEach((button) => button.addEventListener("click", () => closeDialog(projectDialog, $("#projectForm")))); document.querySelectorAll("[data-close-artifact-dialog]").forEach((button) => button.addEventListener("click", () => closeDialog(artifactDialog, $("#artifactForm")))); document.querySelectorAll("[data-close-upload-dialog]").forEach((button) => button.addEventListener("click", closeUploadDialog)); document.querySelectorAll("[data-close-integration-dialog]").forEach((button) => button.addEventListener("click", () => closeDialog(integrationDialog, $("#integrationForm"))));
projectDialog.addEventListener("click", (event) => { if (event.target === projectDialog) closeDialog(projectDialog, $("#projectForm")); }); artifactDialog.addEventListener("click", (event) => { if (event.target === artifactDialog) closeDialog(artifactDialog, $("#artifactForm")); }); uploadDialog.addEventListener("click", (event) => { if (event.target === uploadDialog) closeUploadDialog(); }); integrationDialog.addEventListener("click", (event) => { if (event.target === integrationDialog) closeDialog(integrationDialog, $("#integrationForm")); }); $("#uploadFiles").addEventListener("change", updateUploadSelection);
$("#projectForm").addEventListener("submit", async (event) => { event.preventDefault(); const name = $("#newProjectName").value.trim(), brief = $("#newProjectBrief").value.trim(); if (!name || !brief) return; try { project = await request("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, brief }) }); viewStage = 0; await refreshProjectList(); closeDialog(projectDialog, $("#projectForm")); render(); say("项目已创建，真实状态文件已保存"); } catch (error) { say(error.message); } });
$("#artifactForm").addEventListener("submit", async (event) => { event.preventDefault(); if (artifactReadOnly) return; const content = $("#artifactContent").value.trim(); if (!content) return; try { project = await request(`/api/projects/${project.id}/artifacts/${project.stages[viewStage].id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content }) }); await refreshProjectList(); closeDialog(artifactDialog, $("#artifactForm")); render(); say("工件已保存为新版本"); } catch (error) { say(error.message); } });
$("#uploadForm").addEventListener("submit", async (event) => { event.preventDefault(); const files = [...$("#uploadFiles").files]; if (!files.length) return; const tooLarge = files.find((file) => file.size > 50 * 1024 * 1024); if (tooLarge) return say(`“${tooLarge.name}”超过 50 MB 限制`); const submit = $("#submitUpload"), originalLabel = submit.innerHTML; submit.disabled = true; try { for (const file of files) { submit.textContent = `正在上传 ${file.name}…`; project = await request(`/api/projects/${project.id}/uploads`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: file.name, type: file.type, kind: $("#uploadKind").value, data: await toBase64(file) }) }); } await refreshProjectList(); closeUploadDialog(); render(); say(`${files.length} 个文件已保存到当前项目`); } catch (error) { say(error.message); } finally { submit.disabled = false; submit.innerHTML = originalLabel; } });
$("#integrationForm").addEventListener("submit", async (event) => { event.preventDefault(); const adapterId = $("#modelAdapter").value; if (!adapterId) { closeDialog(integrationDialog, $("#integrationForm")); return; } const button = $("#testIntegration"), originalLabel = button.innerHTML; button.disabled = true; button.textContent = "正在连接…"; try { integration = await request("/api/integrations/models/test", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ adapterId, apiKey: $("#openAiApiKey").value, baseUrl: $("#compatibleBaseUrl").value, model: $("#compatibleModel").value }) }); closeDialog(integrationDialog, $("#integrationForm")); render(); say("模型中心已连接；后续步骤将自动调用合适模型。"); } catch (error) { say(error.message); } finally { button.disabled = false; button.innerHTML = originalLabel; } });
async function boot() { try { await Promise.all([refreshProjectList(), refreshIntegration()]); project = await request(`/api/projects/${projects[0].id}`); viewStage = project.currentStage; render(); } catch (error) { say(`无法连接本地服务：${error.message}`); } }
boot();
